### PR TITLE
Add watchOS target

### PR DESCRIPTION
**Pull request by hohteri**
Add watchOS target to enable Firebase Firestore watchOS support.

### CODE REVIEW

**Comment by hohteri** [comment]
@googlebot I fixed it.

**Comment by hohteri** [comment]
I got this response from`pod spec lint`, I hope it is okay as I can't add the tag to the original repo

> mbp:leveldb-library-podspec hohteri$ pod spec lint leveldb-library.podspec --skip-import-validation
>
>  -> leveldb-library (1.22.1)
>     - WARN  | source: The version should be included in the Git tag.
>     - NOTE  | xcodebuild:  note: Using new build system
>     - NOTE  | xcodebuild:  note: Planning build
>     - NOTE  | xcodebuild:  note: Constructing build description
>     - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'leveldb-library' from project 'Pods')

**Comment by paulb777** [comment]
@hohteri The warning is ok, but we'll need to look more closely at the last note.

**Comment by hohteri** [comment]
I get the same on the latest released version:

> mbp:leveldb-library-podspec hohteri$ git checkout d016be88f655da738f10ede3292d0e7de8c843e6
> Note: checking out 'd016be88f655da738f10ede3292d0e7de8c843e6'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at d016be8 Upgrade LevelDB to 1.22 (#9)
> mbp:leveldb-library-podspec hohteri$ pod spec lint leveldb-library.podspec --skip-import-validation
> 
>  -> leveldb-library (1.22)
>     - NOTE  | xcodebuild:  note: Using new build system
>     - NOTE  | xcodebuild:  note: Planning build
>     - NOTE  | xcodebuild:  note: Constructing build description
>     - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'leveldb-library' from project 'Pods')
> 
> Analyzed 1 podspec.
> 
> leveldb-library.podspec passed validation.

**Comment by ryanwilson** [comment]
Hi @hohteri - sorry for the embarrassingly long delay here. I put up #11 but realized that this is essentially identical... if you're able, do you mind copying the 2 comments from my PR and we can land this one instead? Although it's just a few lines, I want to make sure you get the contribution here if you still are able and willing to land it.

Thanks!

**Comment by hohteri** [comment]
@ryanwilson noted, I’ll update this PR. Give me a day or two if you can. Thanks.

**Comment by ryanwilson** [comment]
> @ryanwilson noted, I’ll update this PR. Give me a day or two if you can. Thanks.

No rush on our end, thank you! 😄

**Comment by paulb777** [comment]
I'll just merge this as is and then add the comments from #11. Thanks @hohteri !

**Pull request merged**
